spring.application.name=practica

# ==========================================
# SERVIDOR
# ==========================================

server.port=8081


# ==========================================
# POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# HIKARI
# ==========================================

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1


# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000


# ==========================================
# POSTALIA
# ==========================================

postalia.api.url=https://postalia.com.mx/api/codigos-postales
postalia.api.key=${POSTALIA_API_KEY}