spring.application.name=practica

spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wcfyshazbvgbhwryexlw
spring.datasource.password=qwer1@ty23#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

postalia.api.url=https://postalia.com.mx/api/codigos-postales
postalia.api.key=${POSTALIA_API_KEY}