spring.application.name=practica

spring.datasource.url=jdbc:postgresql://localhost:5432/nominas
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

postalia.api.url=https://postalia.com.mx/api/codigos-postales
postalia.api.key=${POSTALIA_API_KEY}